apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    
    [log]
    mode = console
    level = info
    
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
    [server]
    http_port = 3000
    domain = localhost
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin
    hide_version = false
    
    [auth]
    disable_login_form = true
    disable_signout_menu = true
    
    [security]
    allow_embedding = true
    cookie_secure = false
    cookie_samesite = lax
    
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Admin
    
    [snapshots]
    external_enabled = false
