apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: deployment-platform
    app.kubernetes.io/component: dashboard
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/single-node-gitops
    targetRevision: HEAD
    path: applications/deployment-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: deployment-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
