apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deployment-platform

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: deployment-platform
  app.kubernetes.io/component: dashboard
