apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: base-infrastructure
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - storage-class.yaml

commonLabels:
  app.kubernetes.io/part-of: single-node-gitops
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  config.kubernetes.io/origin: |
    configuredIn: infrastructure/base/kustomization.yaml
    configuredBy:
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
