---
# K3s automatically creates the local-path StorageClass
# This file contains configurations that will be applied separately
# Since StorageClass parameters can't be modified after creation

# StorageClass Annotations - Will be applied separately in install.sh
# annotations:
#   storageclass.kubernetes.io/is-default-class: "true"

# Standard PV and PVC configuration for platform storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-storage-pv
  labels:
    app.kubernetes.io/name: platform-storage
    app.kubernetes.io/part-of: single-node-gitops
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /opt/platform-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
