---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  labels:
    app.kubernetes.io/name: local-path-provisioner
    app.kubernetes.io/part-of: single-node-gitops
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    config.kubernetes.io/description: "Local path storage for single-node deployment"
provisioner: rancher.io/local-path
parameters:
  hostPath: /opt/local-path-provisioner
  nodePath: /var/lib/rancher/k3s/storage
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
