apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/part-of: single-node-gitops
    environment: production
  annotations:
    config.kubernetes.io/description: "Production Longhorn distributed storage"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "strict-local"
  # Production optimizations
  diskSelector: "ssd,nvme"
  nodeSelector: "storage=enabled"
