apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring-stack
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - prometheus/
  - grafana/
  - loki/

commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  config.kubernetes.io/origin: |
    configuredIn: applications/monitoring/kustomization.yaml
    configuredBy:
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
