apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.twun.io
    targetRevision: 2.2.2
    chart: docker-registry
    helm:
      values: |
        service:
          type: NodePort
          nodePort: 30500
        persistence:
          enabled: true
          storageClass: local-path
          size: 10Gi
        secrets:
          htpasswd: ""
        configData:
          storage:
            filesystem:
              rootdirectory: /var/lib/registry
          auth:
            htpasswd:
              realm: Registry
              path: /auth/htpasswd
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
