apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-template
spec:
  hard:
    # CPU limits
    requests.cpu: "2"
    limits.cpu: "4"
    
    # Memory limits
    requests.memory: 2Gi
    limits.memory: 4Gi
    
    # Storage limits
    requests.storage: 20Gi
    
    # Pod count limits
    pods: "20"
    
    # Object count limits
    services: "10"
    configmaps: "20"
    secrets: "20"
    persistentvolumeclaims: "10"
